CREATE TABLE ARTICLE
(
	SEQ INT AUTO_INCREMENT
		PRIMARY KEY,
	POST_TITLE VARCHAR(50) NOT NULL COMMENT '제목',
	POST_CONTENT TEXT NOT NULL COMMENT '내용',
	CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일시',
	UPDATE_DATE DATETIME NULL COMMENT '수정일시'
)
COMMENT '게시글';

INSERT INTO ARTICLE (POST_TITLE, POST_CONTENT)
VALUES ('테스트 게시글 1', '테스트 게시글 1');
INSERT INTO ARTICLE (POST_TITLE, POST_CONTENT)
VALUES ('테스트 게시글 2', '테스트 게시글 2');
INSERT INTO ARTICLE (POST_TITLE, POST_CONTENT)
VALUES ('테스트 게시글 3', '테스트 게시글 3');

CREATE TABLE COMMENT
(
	SEQ INT AUTO_INCREMENT COMMENT '일련번호'
		PRIMARY KEY,
	ARTICLE_SEQ INT NOT NULL COMMENT '게시글 일련번호',
	COMMENT_CONTENT TEXT NOT NULL COMMENT '댓글 내용',
	CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일시',
	UPDATE_DATE DATETIME NULL COMMENT '수정일시'
)
COMMENT '댓글';

INSERT INTO COMMENT (ARTICLE_SEQ, COMMENT_CONTENT)
VALUES (1, '테스트1의 댓글1');
INSERT INTO COMMENT (ARTICLE_SEQ, COMMENT_CONTENT)
VALUES (1, '테스트1의 댓글2');
INSERT INTO COMMENT (ARTICLE_SEQ, COMMENT_CONTENT)
VALUES (1, '테스트1의 댓글3');

INSERT INTO COMMENT (ARTICLE_SEQ, COMMENT_CONTENT)
VALUES (2, '테스트2의 댓글1');

INSERT INTO COMMENT (ARTICLE_SEQ, COMMENT_CONTENT)
VALUES (3, '테스트3의 댓글1');
INSERT INTO COMMENT (ARTICLE_SEQ, COMMENT_CONTENT)
VALUES (3, '테스트3의 댓글2');

CREATE TABLE GRP
(
  SEQ INT AUTO_INCREMENT COMMENT '일련번호'
    PRIMARY KEY,
  PAR_SEQ INT COMMENT '부모일련번호',
  GRP_NAME VARCHAR(50) NOT NULL COMMENT '그룹명',
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일시',
  UPDATE_DATE DATETIME NULL COMMENT '수정일시'
)
COMMENT '그룹';

INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (NULL, '그룹1');
INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (NULL, '그룹2');
INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (NULL, '그룹3');

INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (1, '그룹1-1');
INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (1, '그룹1-2');
INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (2, '그룹2-1');
INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (2, '그룹2-2');
INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (2, '그룹2-3');
INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (3, '그룹3-1');
INSERT INTO GRP (PAR_SEQ, GRP_NAME)
VALUES (3, '그룹3-2');