# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST {{host}}/article
Content-Type: application/json

{
  "postTitle": "테스트 제목5",
  "postContent": "테스트 내용5"
}

###
GET {{host}}/article
Accept: application/json

###

PUT {{host}}/article
Content-Type: application/json

{
  "seq": 1,
  "postTitle": "수정된 테스트 제목5",
  "postContent": "수정된 테스트 내용5"
}

###